Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -10,30 +10,72 @@ jobs:
     runs-on: self-hosted
 
     steps:
+
+      # 1. Checkout source code
       - name: Checkout code
         uses: actions/checkout@v4
-        
+
+      # 2. Check Docker Hub secrets
+      - name: Check Docker Hub secrets
+        run: |
+          if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
+            echo "ERROR: DOCKER_USERNAME is NOT set"
+            exit 1
+          else
+            echo "DOCKER_USERNAME is set"
+          fi
+
+          if [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
+            echo "ERROR: DOCKER_PASSWORD is NOT set"
+            exit 1
+          else
+            echo "DOCKER_PASSWORD is set"
+          fi
+
+      # 3. Login to Docker Hub
       - name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
 
+      # 4. Build Docker image
       - name: Build Docker image
         run: |
           docker build \
             -t ${{ secrets.DOCKER_USERNAME }}/nginx-cicd:${{ github.sha }} .
 
+      # 5. Push Docker image to Docker Hub
       - name: Push Docker image
         run: |
           docker push \
             ${{ secrets.DOCKER_USERNAME }}/nginx-cicd:${{ github.sha }}
 
+      # 6. Check Kubernetes connection
+      - name: Check Kubernetes
+        run: |
+          kubectl get nodes
+          kubectl get pods
+
+      # 7. Deploy new image to Kubernetes
       - name: Deploy to Kubernetes
         run: |
           kubectl set image deployment/nginx-app \
             nginx=${{ secrets.DOCKER_USERNAME }}/nginx-cicd:${{ github.sha }}
 
+      # 8. Wait for rollout
       - name: Verify deployment
         run: |
           kubectl rollout status deployment/nginx-app
+
+      # 9. Show final status
+      - name: Deployment status
+        run: |
+          echo "===== Deployment ====="
+          kubectl get deployment nginx-app
+
+          echo "===== Pods ====="
+          kubectl get pods
+
+          echo "===== Service ====="
+          kubectl get service nginx-service
